export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const ACCESS_KEY = 'gTpE5hqALzSLEhDKdr2tZs3tcE8ERhHAISBunMM1eyk';
export const SECRET_KEY = 'o6YtfTWzaUOey1RszJJ1llk4wJDhIaH760dOPIWwRg4';
export const REDIRECT_URI = 'http://127.0.0.1:5500/';
export const RESPONSE_TYPE = 'code';
export const SCOPE =  'public read_user read_photos write_likes';